server:
  port: 8081

spring:
  application:
    name: AUTHENTICATION-SERVICE
  mongodb:
    uri: mongodb+srv://admin:admin@db-test.eqxxnat.mongodb.net/bt-management-db?authSource=admin&retryWrites=true&w=majority

user:
  name: Shubham Patel
  email: sptel.ai@gmail.com
  password: admin
  address:
    state: Madhya Pradesh
    city: Sagar
    pincode: 470002
    contacts:
      - 9389112183
      - 9389112183

resilience4j:
  circuitbreaker:
    instances:
      horizonService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
